image:
  file: .gitpod.Dockerfile

tasks:
  - name: Run All Services
    command: ./start-all.sh

ports:
  - port: 8761
    onOpen: open-preview
    name: Eureka
  - port: 8081
    onOpen: ignore
    name: User Service
  - port: 8082
    onOpen: ignore
    name: Product Service
  - port: 8083
    onOpen: ignore
    name: Wishlist Service
  - port: 8080
    onOpen: open-preview
    name: API Gateway
