 # Use Java 17 base image
# FROM openjdk:17-jdk-slim

# # Set working directory
# WORKDIR /app

# # Copy the built jar file into the image
# COPY target/*.jar app.jar

# # Expose port (change it if your service uses a different port)
# EXPOSE 8082

# # Command to run the application
# ENTRYPOINT ["java", "-jar", "app.jar"]
